const nameGirl = 'To : EC Girls';
const giftUrl = 'https://www.facebook.com/groups/165460116804572';
const eventName = 'Happy 20/10 !!!';
const titleCard = 'For EC girls';
const contentCard = '</br>Cảm ơn cậu đã đến bên chúng tớ ! </br> Mọi cảm giác và mọi khoảnh khắc hạnh phúc sẽ không được thực sự trọn vẹn nếu như thiếu cậu trong đó! Chúc cậu có ngày 20/10 hạnh phúc. </br></br>         From hacker lỏ EC boy with luv !';
const giftImage = 'test2010.jpg';
const giftBg = 'valentines.jpg'
const base64 = '';
const giftImageBase64 = "data:image/jpg;base64, " + base64;
